language: php

php:
  - 5.5
  - 5.4

install:
  - yes '' | pecl install eio
  - composer install

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
